addr = '0.0.0.0:8090'
signup_enabled = true
title = 'Bmtdblog'
session_secret = 'Bmtdblog'
domain = 'http://localhost:8090'
file_server = 'smms'
notify_emails = ''
page_size = 10
public = 'static'
view = 'views/**/*.html'
dir = '.'

[database]
dsn = 'cp:cp123456@tcp(mysql:3306)/bmtdblog?charset=utf8mb4&parseTime=True&loc=Local'

[seo]
description = 'Bmtdblog, just my toy'

[seo.author]
name = 'hvfwdemc'
email = '3138910969@qq.com'

[qiniu]
enabled = true
accesskey = ''
secretkey = ''
fileserver = ''
bucket = 'Bmtdblog'

[smms]
enabled = true
apiurl = 'https://sm.ms/api/v2/upload'
apikey = ''

[redis]
enabled = true
addr = 'redis:6379'
password = ''
db = 0
pool_size = 10

[elasticsearch]
enabled = true
url = 'http://elasticsearch:9200'
username = ''
password = ''
index_name = 'bmtdblog_posts'

[github]
enabled = true
clientid = 'Iv23likeZWSmInrQcd1R'
clientsecret = '2d9032f934f8cf850de78054beb4bf19046e03c3'
redirecturl = 'http://115.120.208.110:8090/oauth2callback'
authurl = 'https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s&prompt=select_account'
tokenurl = 'https://github.com/login/oauth/access_token'
scope = ''

[smtp]
enabled = true
username = '3138910969@qq.com'
password = 'fojcpbdomonmdggf'
host = 'smtp.qq.com:587'

[[navigators]]
title = 'Posts'
url = '/index'
target = ''

[[navigators]]
title = 'AboutMe'
url = '/page/1'
target = ''

[[navigators]]
title = 'RSS'
url = '/rss'
target = '_blank'

[[navigators]]
title = 'Subscribe'
url = '/subscribe'
target = ''

[backup]
enabled = true
backup_key = ''

[tls]
enabled = false
auto_cert = false
domain = ''
email = ''
cert_file = ''
key_file = ''
cert_dir = 'certs'
